#ifndef LOGFS_CONFIG_H
#define LOGFS_CONFIG_H

#define LogFS_NAME "LOGFS"
#define LogFS_VERSION 1

// FS GLOBAL CONFIG LOGFS v1
uint16_t DEFAULT_PAGE_SIZE = 1024;
uint16_t DEFAULT_MAX_FILES_AMOUNT = 128;
uint16_t HEADER_SIZE = 32;


#endif
