#ifndef LOGFS_CONFIG_H
#define LOGFS_CONFIG_H

#define LogFS_NAME "LOGFS"
#define LogFS_VERSION 1
#define LogGS_FILE_NAME_LENGTH 13

// FS GLOBAL CONFIG LOGFS v1
#define DEFAULT_PAGE_SIZE 1024
#define DEFAULT_MAX_FILES_AMOUNT 128
#define HEADER_SIZE 32

enum {
  LOGFS_OK = 0,
  LOGFS_ERR_NOT_FORMATTED,
  LOGFS_ERR_DIFFERENT_VERSION,
  LOGFS_ERR_LOW_SPACE_FILE_TABLE,
  LOGFS_ERR_LOW_SPACE_PAGES,

  LOGFS_ERR_LONG_FILE_NAME,
  LOGFS_ERR_FILE_NOT_FOUND,
  LOGFS_ERR_FILE_NOT_OPENED
};

#endif
